userName = input("What's your Name?: ")
favFood = input("Tell me your favorite food?: ")
favMusic = input("What's you favorite music?: ")
whereLive = input("Where do you live?: ")
skill = input("enjoy anything?? ")

print("So far my dear, your name is ")
print(userName)

print("Your preferences include")
print("> Food: ")
print(favFood)
print("> Music: ")
print(favMusic)
print("You live in ")
print(whereLive)
print("Your main mind-fixation is ")
print(skill)
print("it's not just a hobby, it's your essence, isn't it?")
